version: '3.5'

services: 
  app:
    build: .
    volumes:
      - ./:/app
    working_dir: /app
    environment:
      NODE_ENV: local #CAMBIARE CON IL PROPIO ENV!
    command: npm run start:dev
networks:
  default:
    external:
      name: nodejsProject